name: PosePonder
favicon: null
layout_spectrum: 0.607385799055919
typography_spectrum: 0.09642934054136276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6249031233601272
  lightness: 0.8507167720235884
  saturation: 0.4372909739613533
  rhythmicContrast: 0.5074303788132966
purpose: []
