name: PosePonder
favicon: null
layout_spectrum: 0.607385799055919
typography_spectrum: 0.75471
title: Posed and Pondered
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#381e21'
    - '#9c4e30'
    - '#f2e6c9'
    - '#cabba5'
    - '#6c8785'
  brandStrength: 0.6249031233601272
  lightness: 0.5
  saturation: 0.4372909739613533
  rhythmicContrast: 0.75
purpose: []
